### PR TITLE
Code.org p5.play extensions - add World object, set version to 1.3.1-cdo

### PR DESCRIPTION
**Pull request by cpirich**
* Expose `World` object from GameLab directly in `p5.play`, with the following properties:
  * `frameRate`
  * `seconds`
  * `width`
  * `height`
  * `mouseX`
  * `mouseY`
  * `allSprites`
  * `frameCount`
* Migrate `World.seconds` test case from code.org's repo

### CODE REVIEW

**Comment by joshlory** [comment]
I know this is something we shipped in Game Lab, and it makes sense to extract it from the code-dot-org repo.  Taking a step back, is there a curriculum reason to have `World.foo` in addition to `foo`?  p5.js seems to favor bare global methods everywhere.

My bias here is that I think we want fewer, more basic APIs crossing the native <-> interpreter boundary.

**Comment by cpirich** [comment]
@joshlory I need to expose this in order to make Gamelab apps "exportable" in a compatible way.

Poorva may recall why we were asked to create the `World` object in the first place. It was a request from program management or the curriculum team. It was one of many places where they wanted to expose it in a different way than p5/p5play - and we followed that guidance for our version in p5/p5play.

At any rate, the blocks in Gamelab expose these properties through the `World` object and I don't think they are planning to change them anytime soon. And even if we did, we'd still need to support the object for any existing projects.

**Comment by poorvasingal** [comment]
I am having a hard time remembering what the reasoning as as well. Like Chris said, though, we need to keep it as is since it's reflected everywhere in our curriculum as such. So we shouldn't be trying to get rid of "World."

**Comment by joshlory** [comment]
Right sorry, I'm not suggesting we get rid of `World`.  I'm more trying to understand where it lives in the p5.play vs. cdo vs cdo-gamelab codebase.

**Comment by cpirich** [comment]
@joshlory the Export work requires that all of the student code runs outside the interpreter. So we are attempting to make our fork of `p5.play` contain the library code needed to run Gamelab apps (written in Code Studio) outside of Code Studio, outside of the interpreter.

**Comment by joshlory** [comment]
There are three layers as far as I can tell:

```
JSInterpreter (cdo repo)
-----------
GameLab
-----------
p5.play
```

Pushing this complexity down to the p5.play level may be the fastest for shipping native Game Lab apps, but isn't necessarily the best outcome for other apps built on p5 and p5.play.  I'm trying to represent those interests as well.

**Comment by cpirich** [comment]
Understood. This was based on a discussion that @islemaster and I had at the start of the summer. It comes down to "what is the purpose of our for of `p5.play`?" It isn't particularly about expediency. I'm not putting code.org specific APIs into our fork of `p5.play` (e.g. `playSound`, `randomNumber`, etc.) But our (earlier) conclusion was all of the changes we made to `p5.play` for the purpose of making it easier to for students to use `p5.play` from within Code Studio belong in our fork (this includes all of the aliases, and in turn, I'd assume, the `World` APIs).

**Pull request merged**
